{% set name = "hatchling" %}
{% set version = "1.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 793c31816d952cee405b83488ce001c719f325d9cda69f1fc4cd750527640ea6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - hatchling = hatchling.cli:hatchling
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    # bootstrapping
    - packaging >=24.2
    - pathspec >=0.10.1
    - pluggy >=1.0.0
    - tomli >=1.2.2  # [py<311]
    - trove-classifiers
  run:
    - packaging >=24.2
    - pathspec >=0.10.1
    - pluggy >=1.0.0
    - python
    - tomli >=1.2.2  # [py<311]
    - trove-classifiers

test:
  imports:
    - hatchling
  commands:
    - pip check
    - hatchling --help
  requires:
    - pip

about:
  home: https://hatch.pypa.io/latest
  summary: Modern, extensible Python build backend
  description: Modern, extensible Python build backend
  dev_url: https://github.com/pypa/hatch/tree/master/backend
  doc_url: https://hatch.pypa.io/latest/plugins/about/#hatchling
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT

extra:
  recipe-maintainers:
    - ofek
  skip-lints:
    - missing_wheel
